version: '3.3'

services:
  steamcmd:
    image: encoren1/steamcmd:${STEAMCMD_TAG:-latest}
    build:
      context: ./steamcmd

  base-insurgency:
    image: encoren1/gameserver:insurgency-${INSURGENCY_BASE_TAG:-latest}
    build:
      context: ./base
      args:
        APPID: 237410
        APPNAME: insurgency

  base-doi:
    image: encoren1/gameserver:doi-${DOI_BASE_TAG:-latest}
    build:
      context: ./base
      args:
        APPID: 462310
        APPNAME: doi

  base-sandstorm:
    image: encoren1/gameserver:sandstorm-${SANDSTORM_BASE_TAG:-latest}
    build:
      context: ./base
      args:
        APPID: 581330
        APPNAME: sandstorm

  insurgency:
    image: insurgency:${INSURGENCY_TAG:-latest}
    build:
      context: ./insurgency
    environment:
      APP_SERVER_NAME: 'Insurgency-Server'
      APP_SERVER_PASSWORD: 'password'
      APP_SERVER_RCONPASSWORD: 'rconp4ss'
      APP_SERVER_PORT: '27018'
      APP_SERVER_MAXPLAYERS: '128'
      APP_SERVER_MAP: 'market_coop'
    volumes:
      - ./insurgency/config.template/:/tmp/insurgency:ro
    ports:
      - "27018:27018"
      - "27018:27018/udp"

  doi:
    image: doi:${DOI_TAG:-latest}
    build:
      context: ./doi
    environment:
      APP_SERVER_NAME: 'Doi-Server'
      APP_SERVER_PASSWORD: 'password'
      APP_SERVER_RCONPASSWORD: 'rconp4ss'
      APP_SERVER_PORT: '27019'
      APP_SERVER_MAXPLAYERS: '128'
      APP_SERVER_MAP: 'bastogne'
    volumes:
      - ./doi/config.template/:/tmp/doi:ro
    ports:
      - "27019:27019"
      - "27019:27019/udp"  


  sandstorm:
    image: sandstorm:${SANDSTORM_TAG:-latest}
    build:
      context: ./sandstorm
    environment:
      APP_SERVER_NAME: 'sandstorm-Server'
      APP_SERVER_PASSWORD: 'password'
      APP_SERVER_RCONPASSWORD: 'rconp4ss'
      APP_SERVER_PORT: '27102'
      APP_SERVER_QUERYPORT: '27131'
      APP_SERVER_MAXPLAYERS: '128'
      APP_SERVER_MAP: 'market_coop'
    ports:
      - "27102:27102"
      - "27102:27102/udp"
      - "27131:27131"
      - "27131:27131/udp"
      - "7777:7777"
      - "7777:7777/udp"
    volumes:
      - ./sandstorm/config.template/:/tmp/sandstorm:ro
    #ports:
    #  - "27018:27018"
    #  - "27018:27018/udp"
