version: '3.3'

services:
  steamcmd:
    image: my-steamcmd:${STEAMCMD_TAG:-latest}
    build:
      context: ./steamcmd
  insurgency-base:
    image: insurgency-base:${INSURGENCY_BASE_TAG:-latest}
    depends_on:
      - steamcmd
    build:
      context: ./base
      args:
        APPID: 237410
        APPNAME: insurgency
  doi-base:
    image: doi-base:${DOI_BASE_TAG:-latest}
    depends_on:
      - steamcmd
    build:
      context: ./base
      args:
        APPID: 462310
        APPNAME: doi
  insurgency:
    image: insurgency:${INSURGENCY_TAG:-latest}
    depends_on:
      - insurgency-base
    build:
      context: ./insurgency
    environment:
      APP_SERVER_NAME: 'Insurgency-Server'
      APP_SERVER_PASSWORD: 'password'
      APP_SERVER_RCONPASSWORD: 'rconp4ss'
      APP_SERVER_PORT: '27018'
      APP_SERVER_MAXPLAYERS: '128'
      APP_SERVER_MAP: 'market_coop'
    volumes:
      - ./insurgency/insurgency/:/tmp/insurgency
      - ./doi/logs:/home/steam/237410/insurgency/logs      
    ports:
      - "27018:27018"
      - "27018:27018/udp"
  doi:
    image: doi:${DOI_TAG:-latest}
    depends_on:
      - doi-base
    build:
      context: ./doi
    environment:
      APP_SERVER_NAME: 'Doi-Server'
      APP_SERVER_PASSWORD: 'password'
      APP_SERVER_RCONPASSWORD: 'rconp4ss'
      APP_SERVER_PORT: '27019'
      APP_SERVER_MAXPLAYERS: '128'
      APP_SERVER_MAP: 'bastogne'
    volumes:
      - ./doi/doi/:/tmp/doi
      - ./doi/logs:/home/steam/462310/doi/logs
    ports:
      - "27019:27019"
      - "27019:27019/udp"  
