#!/bin/bash
set -x

cd ${APPDIR}

/bin/merge_config

if ! [ "x${APP_SERVER_TOKEN}" = "x" ]; then
	echo "sv_setsteamaccount ${APP_SERVER_TOKEN}" > ${APPDIR}/${APP_GAME_NAME}/cfg/autoexec_steamaccount.cfg
	STEAM_SERVER_TOKEN="+exec autoexec_steamaccount.cfg"
fi

if [ "$USE_SRCDS" = "true" ]; then
	if ! [ "x${APP_GAME_NAME}" = "x" ]; then
		APP_GAME_NAME="-game ${APP_GAME_NAME}"
	fi

	./srcds_run -console ${APP_GAME_NAME} ${APP_SRCDS_FLAGS} -nohltv ${STEAM_SERVER_TOKEN} +maxplayers ${APP_SERVER_MAXPLAYERS} ${APP_SRCDS_FLAGS} +map ${APP_SERVER_MAP} -port ${APP_SERVER_PORT}
else
	echo "Unknown Server Startup Usage"
	exit 1
fi
