#!/bin/bash
set -x

APP_GAME_NAME=${APPNAME}
APPDIR=${HOME}/${APPID}

#This also need to be adapted 
#/bin/merge_config

#if ! [ "x${APP_SERVER_TOKEN}" = "x" ]; then
#	echo "sv_setsteamaccount ${APP_SERVER_TOKEN}" > ${APPDIR}/${APP_GAME_NAME}/cfg/autoexec_steamaccount.cfg
#	STEAM_SERVER_TOKEN="+exec autoexec_steamaccount.cfg"
#fi


cd ${APPDIR}
${APPDIR}/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping ${APP_SERVER_MAP}?MaxPlayers=${APP_SERVER_MAXPLAYERS}?Password=${APP_SERVER_PASSWORD} -hostname=${APP_SERVER_NAME} -Port=${APP_SERVER_PORT} -QueryPort=${APP_SERVER_QUERYPORT} ${APP_EXTRA_ARGS}
