#!/bin/bash
set -x

APP_GAME_NAME=${APPNAME}
APPDIR=${HOME}/${APPID}

#This also need to be adapted 
#/bin/merge_config

#if ! [ "x${APP_SERVER_TOKEN}" = "x" ]; then
#	echo "sv_setsteamaccount ${APP_SERVER_TOKEN}" > ${APPDIR}/${APP_GAME_NAME}/cfg/autoexec_steamaccount.cfg
#	STEAM_SERVER_TOKEN="+exec autoexec_steamaccount.cfg"
#fi


cd ${APPDIR}
#Command example
#Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Oilfield?Scenario=Scenario_Refinery_Push_Security \
#?MaxPlayers=28 -Port=27102 -QueryPort=27131 -log -hostname="My Server"
${APPDIR}/srcds_run -game ${APP_GAME_NAME} ${APP_SRCDS_FLAGS} -nohltv ${STEAM_SERVER_TOKEN} +maxplayers ${APP_SERVER_MAXPLAYERS} +map ${APP_SERVER_MAP} -port ${APP_SERVER_PORT} ${APP_EXTRA_ARGS}
