#!/bin/bash
set -x

APP_GAME_NAME=${APPNAME}
APPDIR=${HOME}/${APPID}
SERVERCMD=${APPDIR}/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping 


#This also need to be adapted 

/bin/merge_config_ue4

cd ${APPDIR} && \
${SERVERCMD} ${APP_SERVER_MAP}?MaxPlayers=${APP_SERVER_MAXPLAYERS}?Password=${APP_SERVER_PASSWORD} -hostname=${APP_SERVER_NAME} -Port=${APP_SERVER_PORT} -QueryPort=${APP_SERVER_QUERYPORT} ${APP_EXTRA_ARGS}
